### ISSUE TITLE
We need to start and stop tracking

### ISSUE THREAD

**Issue by EorEquis** [ClutchplateDude/OpenAstroTracker#10]
Many ASCOM clients are expecting to be able to know and set if the mount is tracking or not.  While not strictly required by the ASCOM standard, many clients will refuse to slew until they can determine tracking state.

Current ASCOM driver "forces" this behaviour, but does not actually know state of mount.

**Comment by EorEquis** [comment]
We can now read tracking, but still have no command to start and stop tracking outside of park/unpark.

**Comment by ClutchplateDude** [comment]
Yes, we do: :MT1# turns it on and :MT0# off.
